version: 2
jobs:
  fetch-and-test:
    machine: true
    node:
      version: 10.11.0
    steps:
      - checkout
      - run:
          name: Pull tests submodule
          command: git submodule init && git submodule update
      - run:
          name: Update submodule
          command: cd tests && git pull origin develop
      - run:
          name: Install npm dependencies
          command: pwd && npm install
      - run:
          name: Run tests
          command: npm run test
  publish-and-push:
    machine: true
    node:
      version: 10.11.0
    steps:
      - checkout
      - run:
          name: Pull tests submodule
          command: git submodule init && git submodule update
      - run:
          name: Update submodule
          command: cd tests && git pull origin develop
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Bump version
          command: npm version patch
      - run:
          name: Setup NPM credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Deploy to npm
          command: npm publish --public
      - run: ./scripts/git-push.sh

workflows:
  version: 2
  test-only:
    filters:
      branches:
        ignore: master
    jobs:
      - fetch-and-test
  test-deploy:
    filters:
      branches:
        only: master
    jobs:
      - publish-and-push